### ISSUE TITLE
Cannot reproduce: Seed usage 

### ISSUE THREAD

**Issue by Timmeey86** [Timmeey86/FS22_ConservationAgriculture#23]
Some players have reported increased seed usage.

For this, the following needs to be tested:
- Seed usage in base game without any mods
- Seed usage in base game with CA
- Seed usage in Precision Farming without other mods
- Seed usage in Precision Farming with CA

**Comment by Timmeey86** [comment]
Test results: with a Väderstad Rapid A800S, sowing one line on an Elmcreek field:

- Base game without CA: finished at 3086 liters
- Base game with CA: finished at 3086 liters
- PF + CA, withered field: finished at 3086 liters
- PF + CA, growing wheat: finished at 3085 liters
- PF, no CA, withered field: finished at 3049 liters
- PF + CA v1.0.5.0 + LFHA ForageOptimat Standard: loads of lua bugs and seed doesn't seem to get used at all

**Comment by timber3000** [comment]
Map is Hanna, IN, fresh start.  Only mod where the map and the giant dlcs+easy dev+real speed limit.

Planting 1 row of canola using Pottinger Terrasem C6F

base+dlc without CA or PF  : 84l
base+dlc+PF without CA :  84l
base+dlc+PF+CA : 84l
base+dlc+ca no PF : 84l

However, after turning on all my mod it took 4239l for the same row.  So i searched a little and it seem that Swathing Addon was the culprit.

Trying it on Elmcrrek however, the amount of seed remain the same with or without Swathing addon.  

So, I don't know.  Maybe because Hanna is a 4x map instead of 2x like Elmcreek???  Removing Swathing Addon did solve the issue on Hanna...

**Comment by Timmeey86** [comment]
@timber3000 Hi there, thanks a lot for taking the time to narrow this down, this is really helpful information.
I'll take a look at the Swathing Addon and see if I can figure out the conflict

**Comment by Timmeey86** [comment]
> Planting 1 row of canola using Pottinger Terrasem C6F

Can you also describe the state of the field you are planting into, please?

**Comment by timber3000** [comment]
My pleasure.  I'm not able to do mod like the one you did.  I appreciate all the effort modders like you put into making FS more realistic.  So if I can help by searching which mod cause a conflict... Well, I'm happy to help.  

The fields where cultivated before sowing as to provide the same situation in both case.

**Comment by Timmeey86** [comment]
@timber3000  Version 1.0.0.8 should fix this:
https://github.com/Timmeey86/FS22_ConservationAgriculture/releases/tag/v1.0.0.8

Please let me know if you detect any other issues
