### ISSUE TITLE
Feature Request: Add cultivators or at least flat cultivators to the fertilization by the mod.

### ISSUE THREAD

**Issue by Hanninho** [Timmeey86/FS22_ConservationAgriculture#25]
Hi,
first of all, thanks for the mod. I find PF makes the use of catch crops very unrewarding as well, so I appreciate the mod.
However, I also see room for improvement here, because undermining the mature catch crops does not add any nitrogen value at all. And at the end of the day, it's just a matter of getting the mature catch crop chopped up and under the soil. Would it therefore be possible to add both classes?

**Comment by Timmeey86** [comment]
If you want to help testing, you can try out the https://github.com/Timmeey86/FS22_ConservationAgriculture/tree/feature/more-fertilization-ways branch where the feature is implemented already

It's a development branch, though, so expect more bugs than usual

**Comment by Timmeey86** [comment]
This is now implemented for base game in https://github.com/Timmeey86/FS22_ConservationAgriculture/tree/feature/fixed-fertilization

Unfortunately, I failed to get it working properly for precision farming since it causes a cycle where the same ground is touched more than once and everything gets fertilized to maximum level.

**Comment by Timmeey86** [comment]
The upcoming release will fully support this for PF and allow adjusting the amount of nitrogen which gets applied
