### ISSUE TITLE
Whatever I plant turns into wheat

### ISSUE THREAD

**Issue by Jan-Legend** [Timmeey86/FS22_ConservationAgriculture#36]
I'm playing on the map Castelnaud, and whatever I'm planting or seeding turns into wheat. I've had this issue with version 1.0.0.8, where it would also change the ground texture to a mulched wheat state and use an insane amount of seed. I saw Issue #32 and updated my version to the latest (12 hours ago as of now, 1.0.1.2). That fixed the ground texture and the seed usage, but whatever I plant still turns into wheat. The log doesn't show anything of use either. It does this with basegame and modded seeders and planters. The state of the field doesn't seem to have an influence either but I'm not sure on that yet, I haven't tried all of them.

When I load the map without any mods other than Easy Development Controls, Additional Game Settings and Conservation Agriculture it works as intended. I have around 200 mods enabled so I was going to enable a group of mods and see if that breaks it, and repeat until it does. That's going to take me a while, so I was hoping that someone would have an idea where to start or what mod(s) could be causing this.

**Comment by Timmeey86** [comment]
This is definitely a mod conflict, highly likely with another script mod.
What I usually do in a situation like that is:
1. Copy the save game into a different slot
2. Move half of the mods out of the mod directory into a temporary folder
3. Start the game and load into the save
4. If the problem persists: Stop the game and repeat from step 2 (with half of the leftover mods).
If the problem is no longer there: Stop the game, move half of the mods which you removed in the previous loop back into the mod folder, then repeat from step 3

After at most 8 loops, you should have found the mod in question, at which point I can look into why it's happening and if I can maybe work around it.

**Comment by Jan-Legend** [comment]
That's a smart way to go about it. Found out that when I turned LFHA ForageOptima Standard off, seeding and planting works as intended. But, when I tested LFHA with Conservation Agrilculture and nothing else, it worked fine. So there's another mod that influences either of the two. Now trying to figure out which one that could be.

**Comment by Jan-Legend** [comment]
It's a combination of LFHA and the Swathing Addon. With both of them enabled together with Conservation Agriculture, it only plants wheat. With only one of them enabled, doesn't matter which of the 2, it works fine. With both enabled and Conservation Agriculture disabled, it works fine too.

**Comment by Timmeey86** [comment]
Now that's an interesting one. I'll look into it as soon as I get the chance, which might only be tomorrow evening, however

**Comment by Jan-Legend** [comment]
No idea if this information helps, but when I changed the SwathingAddon.onStartMission function in the SwathingAddon mod, and set it oat when terrainDataPlaneId == nil, it would plant everything as oat. I couldn't find where and why the fruitType.terrainDataPlaneId get set to nil or invalid data in either of the mods. It does this on basegame and modded maps. If there's anything I can do to make it easier for you to look into later this week, then let me know. I'm not a modder myself, but am a software dev. so figuring out what's doing what and where isn't too hard.

**Comment by Timmeey86** [comment]
Ah that perfectly explains it then:

- LFHA ForageOptima Standard adds a new fruit type without adding an associated density map.
- I made a workaround for this by skipping such fruit types (see [here](https://github.com/Timmeey86/FS22_ConservationAgriculture/blob/a7aa2d7e3eee19be086e8ba2e53f86d57d7be974/scripts/specializations/CoverCropUtils.lua#L243))
- SwathingAddon also made a workaround for this by assigning the wheat density map to such fruit types
- This in turn makes it so my mod no longer ignores that fruit type, since the `terrainDataPlaneId` is no longer `nil`

=> I'm gonna have to find a different attribute which tells me the fruit type should be ignored

**Comment by Timmeey86** [comment]
Should be fixed in the most recent commit

I won't create a release yet since I noticed heavily increased seed usage when field creation is turned on, but I haven't found a fix for that yet (might also only happen on certain maps, haven't had the time to test lately)

**Comment by Jan-Legend** [comment]
Awesome, that explains it indeed. I saw the issue you had raised on LFHA, too bad there's no response as to solving the missing density map, but at least this will work. 

If I can help with testing the increased seed usage, I'm more than happy to do so.

**Comment by Timmeey86** [comment]
uhm basically just turn on field creation on a seeder on any map and see if seeds start going down like mad (like 10% per 10 meters or so)

**Comment by Jan-Legend** [comment]
Sorry it took a while. Didn't have much time and had some issues with loading a game running out of memory (unrelated to this or the other 2 mods), but wanted to fix that first. I've not been able to do much testing, will hopefully be able to do that today, but I did notice that direct seeding while creating a field does indeed use a bunch of seed.

**Comment by Timmeey86** [comment]
As you can see I don't have a lot of time myself. I do however believe I have know fixed the extreme seed usage for good in the most recent commit

**Comment by Timmeey86** [comment]
I created a new release and will likely upload that one to modhub: https://github.com/Timmeey86/FS22_ConservationAgriculture/releases/tag/v1.0.1.3

**Comment by Jan-Legend** [comment]
Hahaha, I guess it's the same for everyone. I can confirm that that fixed the issue, great work, much appreciated, thanks!
